# Generated by Django 2.2.12 on 2021-07-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latin_name', models.CharField(max_length=100, unique=True)),
                ('isNative', models.BooleanField(default=True)),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_base.Plants')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('shape', models.CharField(choices=[('AR', 'Arrow-Shaped'), ('CP', 'Compound'), ('DL', 'Deltoid'), ('HT', 'Heart-Shaped'), ('LA', 'Lanecolate'), ('LI', 'Linear'), ('LB', 'Lobed'), ('OB', 'Oblong'), ('OL', 'Oval'), ('TL', 'Three-leaved')], max_length=2)),
                ('desc', models.TextField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_base.Plants')),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('colors', models.TextField()),
                ('desc', models.TextField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_base.Plants')),
            ],
        ),
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, null=True)),
                ('colors', models.TextField()),
                ('desc', models.TextField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plant_base.Plants')),
            ],
        ),
    ]
