# Generated by Django 2.2.12 on 2021-07-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_base', '0002_auto_20210731_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='shapes',
            field=models.CharField(choices=[('AR', 'Arrow-Shaped'), ('CP', 'Compound'), ('DL', 'Deltoid'), ('HT', 'Heart-Shaped'), ('LA', 'Lanecolate'), ('LI', 'Linear'), ('LB', 'Lobed'), ('OB', 'Oblong'), ('OL', 'Oval'), ('TL', 'Three-leaved')], max_length=2, null=True),
        ),
    ]
