# Generated by Django 2.2.12 on 2021-07-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_base', '0003_auto_20210731_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='shapes',
            field=models.TextField(),
        ),
    ]
