# Generated by Django 2.2.12 on 2021-08-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_base', '0004_auto_20210731_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berries',
            name='image_name',
            field=models.CharField(default='None.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowers',
            name='image_name',
            field=models.CharField(default='None.jpg', max_length=50),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='image_name',
            field=models.CharField(default='None.jpg', max_length=50),
        ),
    ]
